apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: 'postgres:16'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: DATABASE_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: DATABASE_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: blog-app-config
                  key: DATABASE_NAME
          volumeMounts:
            - name: postgresdata
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: blog-app
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP